consume_stk_api/Authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
# from .views import CustomPasswordResetView

from . import views
from .views import SignUpView
# from .views import CustomLoginView  # Import your custom view

app_name = 'Authentication'

urlpatterns = [
        path('', views.index, name='index'),

        path('signup/', SignUpView.as_view(), name='signup_tutor'),

        # Built-in Django auth views
        path('login/', views.custom_login, name='login_user'),
        path('logout/',views.logout_user, name='logout_user'),
        # path('logout/', auth_views.LogoutView.as_view(), name='logout'),

        # Password reset views
        path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset'),
        path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='auth_app/password_reset_done.html'), name='password_reset_done'),
        path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='auth_app/password_reset_confirm.html'), name='password_reset_confirm'),
        path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='auth_app/password_reset_complete.html'), name='password_reset_complete'),

        ]

consume_stk_api/consume_stk_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/account/', include('django.contrib.auth.urls')),  # Built-in auth URLs

    path('', include('stk.urls')),
    path('auth/', include('Authentication.urls'), name='Authentication')

]

consume_stk_api/stk/urls.py
from django.urls import path
from . import views

app_name = 'stk'

urlpatterns = [
        path('init_stk/', views.init_stk, name='stk'),
        path('', views.stkpush, name='stkpush'),
        path('lnmo-callback', views.incoming, name='callback'),
        ]

consume_stk_api/Authentication/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models

class CustomUser(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]

    email = models.EmailField(unique=True, blank=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=False)
    nationality = models.CharField(max_length=100, blank=False)
    # Override the groups field
    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to.',
        related_name='custom_user_set',
        related_query_name='custom_user',
    )

    # Override the user_permissions field
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='custom_user_set',
        related_query_name='custom_user',
    )

    def __str__(self):
        return self.username

consume_stk_api/Authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username','email', 'gender', 'nationality', 'password1', 'password2')

consume_stk_api/Authentication/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.views.generic import CreateView
from django.urls import reverse_lazy, reverse
from .forms import SignUpForm

from django.views import View
from django.contrib.auth import login,logout, authenticate
# Create your views here.

def index(request):
    return HttpResponse("hello Authentication")

class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('Authentication:login_user')
    template_name = 'tutor_signup.html'

    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"{field.capitalize()}: {error}")
        return super().form_invalid(form)

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Account created successfully!")
        return response

def custom_login(request):
    if request.method == 'POST':
        username = request.POST.get('Username')
        password = request.POST.get('Password')
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            
            # Determine the redirect URL
            if user:
                redirect_url = reverse('stk:stkpush')
            else:
                redirect_url = '/'
            
            # Return a response with HX-Redirect header
            response = HttpResponse()
            response['HX-Redirect'] = redirect_url
            return response
        else:
            return render(request, 'loginresult.html')
    
    return render(request, 'login.html')

def redirect_user(user):
        return redirect('/')


def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out')

    return redirect('Authentication:login_user')

consume_stk_api/Authentication/templates/login.html
<!doctype html>
{% load widget_tweaks %}
{% load static %}
<html lang="en">
  <head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'styles/parent_signup.css' %}">
    <link rel='icon' href="{% static '/images/logo.jpeg'%}">
    <script src="https://unpkg.com/htmx.org@1.7.0"></script>
  </head>
  <body>
    <section class="ftco-section d-flex justify-content-center align-items-center min-vh-100">
      <div class="container">
	<div class="row justify-content-center">
	  <div class="col-md-7 col-lg-5">
	    <div class="login-wrap shadow p-4 rounded">
	      <div class="icon d-flex align-items-center justify-content-center mb-4">
		<span class="fa fa-user-o"></span>
	      </div>
	      <h3 class="text-center mb-4">Sign In</h3>

	      <div style="">
		{% if messages %}
		{% for message in messages %}
		{% if "success" in message.tags %}
		<span class="alert alert-success" style="color: green; position:inherit; display:block;" >{{ message }}</span>
		{% else %}
		<span class="alert alert-danger" style="color: #721c24; position:inherit; display:block;"><strong>{{ message }}</strong> please try again</span>
		{% endif %}
		{% endfor %}
		{% endif %}
	      </div>



	      {% if next %}
	      {% if user.is_authenticated %}
	      <p>Your account doesn't have access to this page. To proceed,
		please login with an account that has access.</p>
	      {% else %}
	      <p>Please login to see this page.</p>
	      {% endif %}
	      {% endif %}

	      <div id="result"></div>

	      <form hx-post="{% url 'Authentication:login_user' %}"
		    hx-target="#result"
		    hx-swap="innerHTML"
		    hx-trigger="submit"
		    class="login-form">
		{% csrf_token %}
		<div class="form-group">
		  <input type="text" class="form-control rounded-left" placeholder="Username" name="Username" required>
		</div>
		<div class="form-group d-flex">
		  <input type="password" class="form-control rounded-left" placeholder="Password" name="Password" required>
		</div>
		<div class="form-group">
		  <button type="submit" class="btn btn-primary w-100">
		    Login
		    <img style="background-color: None;" src="{% static 'images/tail-spin.svg' %}" class="htmx-indicator" width="20px" height="20px">
		  </button>
		</div>
		<div id="result"></div>
		<div class="form-group d-flex justify-content-between align-items-center">
		  <label class="checkbox-wrap checkbox-primary">Remember Me
		    <input type="checkbox" checked>
		  </label>
		  <a href="{% url 'Authentication:password_reset' %}" class="text-right">Forgot Password</a>
		</div>
	      </form>
	      <!-- Add Sign-Up Options -->
	      <div class="text-center mt-3">
		<p>Don't have an account?</p>
		<a href="{% url 'Authentication:signup_tutor' %}" class="btn btn-outline-secondary w-100">Sign up as Tutor</a>
	      </div>
	    </div>
	  </div>
	</div>
      </div>
    </section>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

consume_stk_api/Authentication/templates/loginresult.html
<span class="alert alert-danger" style="color: #721c24; position:inherit; display:block;"><strong>Invalid username or password.</strong> please try again</span>		
</div>	

consume_stk_api/Authentication/templates/parent_signup.html
<!doctype html>
{% load widget_tweaks %}
{% load static %}
<html lang="en">
  <head>
    <title>Signup</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/styles/parent_signup.css' %}">
    <link rel='icon' href="{% static '/images/logo.jpeg'%}">
  </head>
  <body>
    <section class="ftco-section d-flex justify-content-center align-items-center min-vh-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-7 col-lg-5">
            <div class="login-wrap shadow p-4 rounded">
              <div class="icon d-flex align-items-center justify-content-center mb-4">
                <span class="fa fa-user-o"></span>
              </div>
			  <h3 class="text-center mb-4">Parent Sign Up</h3>
			  {% if messages %}
			  <div class="messages">
				  {% for message in messages %}
				  <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
					  {{ message }}
				  </div>
				  {% endfor %}
			  </div>
			  {% endif %}

              <form action="#" method="post" class="login-form">
				  {% csrf_token %}
                <div class="form-group">
                  <!-- <input type="text" class="form-control rounded-left" placeholder="Firstname" required> -->

		{% render_field form.username class="form-control rounded-left" placeholder="Username" %}
                </div>
                <div class="form-group">
                  <!-- <input type="text" class="form-control rounded-left" placeholder="Lastname" required> -->
				  
		{% render_field form.first_name class="form-control rounded-left" placeholder="First Name" %}
                </div>
                <div class="form-group">
                  <!-- <input type="email" class="form-control rounded-left" placeholder="Email" required> -->
		{% render_field form.last_name class="form-control rounded-left" placeholder="Last Name" %}
                </div>
                <div class="form-group">
                  <!-- <input type="text" class="form-control rounded-left" placeholder="Nationality" required> -->
		{% render_field form.email class="form-control rounded-left" placeholder="Email" %}
                </div>
                <div class="form-group">
                  <!-- <input type="password" class="form-control rounded-left" placeholder="Password" required> -->
		{% render_field form.nationality class="form-control rounded-left" placeholder="Nationality" %}
                </div>
                <div class="form-group">
                  <!-- <input type="password" class="form-control rounded-left" placeholder="Password" required> -->
		{% render_field form.password1 class="form-control rounded-left" placeholder="Password" %}
                </div>
                <div class="form-group">
                  <!-- <input type="password" class="form-control rounded-left" placeholder="Password" required> -->
		{% render_field form.password2 class="form-control rounded-left" placeholder="Confirm Password" %}
                </div>
                <div class="form-group">
                  <button type="submit" class="btn btn-primary w-100">Sign Up</button>
                </div>
                <div class="form-group d-flex justify-content-between align-items-center">
									<label class="checkbox-wrap checkbox-primary mt-3">Remember Me
										<input type="checkbox" checked>
									</label>
									
									<a href="{% url 'Authentication:login_user' %}" class="btn btn-secondary">Go to Login</a>
								</div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

consume_stk_api/Authentication/templates/tutor_signup.html
<!doctype html>
{% load widget_tweaks %}
{% load static %}
<html lang="en">
	<head>
		<title>Tutor Signup</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel='icon' href="{% static '/images/logo.jpeg'%}">
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static '/styles/parent_signup.css' %}">
	</head>
	<body>
		<section class="ftco-section d-flex justify-content-center align-items-center min-vh-100">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-md-7 col-lg-5">
						<div class="login-wrap shadow p-4 rounded">
							<div class="icon d-flex align-items-center justify-content-center mb-4">
								<span class="fa fa-user-o"></span>
							</div>
							<h3 class="text-center mb-4">Tutor Sign Up</h3>
							{% if messages %}
							<div class="messages">
								{% for message in messages %}
								<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
									{{ message }}
								</div>
								{% endfor %}
							</div>
							{% endif %}
							<form action="#" method="post" class="login-form">
								{% csrf_token %}
								<div class="form-group">
									

									{% render_field form.username class="form-control rounded-left" placeholder="Username" %}
								</div>
								<div class="form-group">
									

									{% render_field form.first_name class="form-control rounded-left" placeholder="First Name" %}
								</div>
								<div class="form-group">
									
									{% render_field form.last_name class="form-control rounded-left" placeholder="Last Name" %}
								</div>
								<div class="form-group">
									
									{% render_field form.email class="form-control rounded-left" placeholder="Email" %}
								</div>
								<div class="form-group">
									
									<select name="{{ form.gender.name }}" id="{{ form.gender.auto_id }}" class="form-control rounded-left">
										<option value="" selected disabled hidden>Select Gender</option>
										{% for value, label in form.gender.field.choices %}
										{% if value %}
										<option value="{{ value }}">{{ label }}</option>
										{% endif %}
										{% endfor %}
									</select>
								</div>
								<div class="form-group">
									
									{% render_field form.nationality class="form-control rounded-left" placeholder="Nationality" %}
								</div>
								<div class="form-group">
									
									{% render_field form.password1 class="form-control rounded-left" placeholder="Password" %}
								</div>
								<div class="form-group">
									
									{% render_field form.password2 class="form-control rounded-left" placeholder="Confirm Password" %}
								</div>
								<div class="form-group">
									<button type="submit" class="btn btn-primary w-100">Sign Up</button>
								</div>
								<div class="form-group d-flex d-sm-flex justify-content-between align-items-baseline">
									<label class="checkbox-wrap checkbox-primary mt-3">Remember Me
										<input type="checkbox" class="mt-3" checked>
									</label>
									
									<a href="{% url 'Authentication:login_user' %}" class="btn btn-secondary">Go to Login</a>
								</div>
								
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>

		
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
	</body>
</html>